# Generated by Django 4.2.5 on 2023-09-16 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commisariat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motovolee',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motovolee',
            name='commissariat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commisariat.commissariat'),
        ),
    ]
