# Generated by Django 4.2.5 on 2023-09-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commisariat', '0003_motovolee_commentaire_alter_motovolee_commissariat'),
    ]

    operations = [
        migrations.AddField(
            model_name='motovolee',
            name='date_vol',
            field=models.DateField(blank=True, null=True),
        ),
    ]
