# Generated by Django 4.2.5 on 2023-09-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commisariat', '0004_motovolee_date_vol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commissariat',
            old_name='responsable',
            new_name='responsable_commissariat',
        ),
        migrations.AddField(
            model_name='commissariat',
            name='email_commissariat',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='commissariat',
            name='telephone_commissariat',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='commissariat',
            name='ville_commissariat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
