# Generated by Django 4.2.5 on 2023-09-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='description',
            field=models.TextField(blank=True, help_text='decrivez votre moto en quelques ligne.', null=True),
        ),
    ]
