# Generated by Django 4.2.5 on 2023-10-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_remove_customuser_adresse_residence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='on_trial',
            field=models.BooleanField(default=True),
        ),
    ]
